// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTaxiService.Data;

#nullable disable

namespace MyTaxiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609111709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyTaxiService.Models.CancellationLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("CancellationFee")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RideId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("CancellationLogs");
            });

            modelBuilder.Entity("MyTaxiService.Models.Driver", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("IsAvailable")
                    .HasColumnType("bit");

                b.Property<string>("LicenseNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("VehicleType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Drivers");
            });

            modelBuilder.Entity("MyTaxiService.Models.Ride", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("DriverID")
                    .HasColumnType("int");

                b.Property<string>("DropLocation")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsCancelled")
                    .HasColumnType("bit");

                b.Property<string>("PickupLocation")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("RideTime")
                    .HasColumnType("datetime2");

                b.Property<int>("UserID")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Rides");
            });

            modelBuilder.Entity("MyTaxiService.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}